//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.09 at 11:40:02 AM BST 
//


package uk.co.thebodyshop.integration.jaxb.store.customer.detail;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LoyaltyMembership complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoyaltyMembership">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProgrammeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProgrammeID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LoyaltyCard" type="{http://thebodyshop/customerDetailSchema}LoyaltyCard" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PointsBalance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoyaltyMembership", propOrder = {
    "programmeName",
    "programmeID",
    "loyaltyCard",
    "pointsBalance"
})
public class LoyaltyMembership {

    @XmlElement(name = "ProgrammeName", required = true)
    protected String programmeName;
    @XmlElement(name = "ProgrammeID", required = true)
    protected String programmeID;
    @XmlElement(name = "LoyaltyCard")
    protected List<LoyaltyCard> loyaltyCard;
    @XmlElement(name = "PointsBalance", required = true)
    protected String pointsBalance;

    /**
     * Gets the value of the programmeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgrammeName() {
        return programmeName;
    }

    /**
     * Sets the value of the programmeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgrammeName(String value) {
        this.programmeName = value;
    }

    /**
     * Gets the value of the programmeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgrammeID() {
        return programmeID;
    }

    /**
     * Sets the value of the programmeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgrammeID(String value) {
        this.programmeID = value;
    }

    /**
     * Gets the value of the loyaltyCard property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the loyaltyCard property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLoyaltyCard().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LoyaltyCard }
     * 
     * 
     */
    public List<LoyaltyCard> getLoyaltyCard() {
        if (loyaltyCard == null) {
            loyaltyCard = new ArrayList<LoyaltyCard>();
        }
        return this.loyaltyCard;
    }

    /**
     * Gets the value of the pointsBalance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPointsBalance() {
        return pointsBalance;
    }

    /**
     * Sets the value of the pointsBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPointsBalance(String value) {
        this.pointsBalance = value;
    }

}
