//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.09 at 11:40:02 AM BST 
//


package uk.co.thebodyshop.integration.jaxb.store.customer.detail;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MarketingMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MarketingMessage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageClass" type="{http://thebodyshop/customerDetailSchema}MessageClassEnum"/>
 *         &lt;element name="MessageType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MessageString" type="{http://thebodyshop/customerDetailSchema}NotNullStringMaxLength512"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MarketingMessage", propOrder = {
    "messageClass",
    "messageType",
    "messageString"
})
public class MarketingMessage {

    @XmlElement(name = "MessageClass", required = true)
    protected MessageClassEnum messageClass;
    @XmlElement(name = "MessageType", required = true)
    protected String messageType;
    @XmlElement(name = "MessageString", required = true)
    protected String messageString;

    /**
     * Gets the value of the messageClass property.
     * 
     * @return
     *     possible object is
     *     {@link MessageClassEnum }
     *     
     */
    public MessageClassEnum getMessageClass() {
        return messageClass;
    }

    /**
     * Sets the value of the messageClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageClassEnum }
     *     
     */
    public void setMessageClass(MessageClassEnum value) {
        this.messageClass = value;
    }

    /**
     * Gets the value of the messageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageType() {
        return messageType;
    }

    /**
     * Sets the value of the messageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageType(String value) {
        this.messageType = value;
    }

    /**
     * Gets the value of the messageString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageString() {
        return messageString;
    }

    /**
     * Sets the value of the messageString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageString(String value) {
        this.messageString = value;
    }

}
