//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.27 at 03:33:52 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://thebodyshop/posOrderSchema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package uk.co.thebodyshop.integration.jaxb.store.order.sales;
