//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.31 at 11:54:39 AM BST 
//


package uk.co.thebodyshop.integration.jaxb.store.customer.search;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LoyaltyMembership complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoyaltyMembership">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProgrammeID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProgrammeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LoyaltyCard" type="{http://thebodyshop/customerSearchSchema}LoyaltyCard"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoyaltyMembership", propOrder = {
    "programmeID",
    "programmeName",
    "loyaltyCard"
})
public class LoyaltyMembership {

    @XmlElement(name = "ProgrammeID", required = true)
    protected String programmeID;
    @XmlElement(name = "ProgrammeName", required = true)
    protected String programmeName;
    @XmlElement(name = "LoyaltyCard", required = true)
    protected LoyaltyCard loyaltyCard;

    /**
     * Gets the value of the programmeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgrammeID() {
        return programmeID;
    }

    /**
     * Sets the value of the programmeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgrammeID(String value) {
        this.programmeID = value;
    }

    /**
     * Gets the value of the programmeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgrammeName() {
        return programmeName;
    }

    /**
     * Sets the value of the programmeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgrammeName(String value) {
        this.programmeName = value;
    }

    /**
     * Gets the value of the loyaltyCard property.
     * 
     * @return
     *     possible object is
     *     {@link LoyaltyCard }
     *     
     */
    public LoyaltyCard getLoyaltyCard() {
        return loyaltyCard;
    }

    /**
     * Sets the value of the loyaltyCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoyaltyCard }
     *     
     */
    public void setLoyaltyCard(LoyaltyCard value) {
        this.loyaltyCard = value;
    }

}
