//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.31 at 11:54:39 AM BST 
//


package uk.co.thebodyshop.integration.jaxb.store.customer.search;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.co.portaltech.tbs.dataprocessing.jaxb.store.customer.search package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.co.portaltech.tbs.dataprocessing.jaxb.store.customer.search
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AdvancedCustomerSearchResponse }
     * 
     */
    public AdvancedCustomerSearchResponse createAdvancedCustomerSearchResponse() {
        return new AdvancedCustomerSearchResponse();
    }

    /**
     * Create an instance of {@link CustomerData }
     * 
     */
    public CustomerData createCustomerData() {
        return new CustomerData();
    }

    /**
     * Create an instance of {@link ResponseStatus }
     * 
     */
    public ResponseStatus createResponseStatus() {
        return new ResponseStatus();
    }

    /**
     * Create an instance of {@link AdvancedCustomerSearchRequest }
     * 
     */
    public AdvancedCustomerSearchRequest createAdvancedCustomerSearchRequest() {
        return new AdvancedCustomerSearchRequest();
    }

    /**
     * Create an instance of {@link CustomerSearchRequest }
     * 
     */
    public CustomerSearchRequest createCustomerSearchRequest() {
        return new CustomerSearchRequest();
    }

    /**
     * Create an instance of {@link CustomerSearchResponse }
     * 
     */
    public CustomerSearchResponse createCustomerSearchResponse() {
        return new CustomerSearchResponse();
    }

    /**
     * Create an instance of {@link LoyaltyMembership }
     * 
     */
    public LoyaltyMembership createLoyaltyMembership() {
        return new LoyaltyMembership();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link LoyaltyCard }
     * 
     */
    public LoyaltyCard createLoyaltyCard() {
        return new LoyaltyCard();
    }

}
