//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.11.07 at 02:29:28 PM GMT
//

package uk.co.thebodyshop.integration.jaxb.store.order.fetch;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for Order complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Order">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Market" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Currency">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[A-Z]{3}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Channel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Customer">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CustomerID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="LoyaltyCardNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="EmailAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Gender" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="CompanyName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AgentID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StoreID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Gift" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="From" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="To" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Cost" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Delivery" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DeliveryMethod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DeliveryCost" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="DeliverySpecialInstructions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="DiscountPromotionCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="DiscountValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Refunded" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CollectionPoint" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CollectionPointMobileNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OrderPromotions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TotalDiscount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="Payments">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Payment" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                             &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="TransactionDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;choice>
 *           &lt;element name="TotalNet" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *           &lt;element name="TotalGross" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;/choice>
 *         &lt;element name="Taxes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Tax" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>double">
 *                           &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="BillingAddress" type="{http://thebodyshop/orderFetchSchema}AddressType"/>
 *         &lt;element name="ShippingAddress" type="{http://thebodyshop/orderFetchSchema}ShippingAddressType"/>
 *         &lt;element name="Entries">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Entry" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="EntryNumber">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="5"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ArticleId">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="18"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="ReturnedQuantity" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                             &lt;element name="GiftWrapped" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="Unit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="UnitPrice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                             &lt;element name="LinePromotions" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Promotion" type="{http://thebodyshop/orderFetchSchema}Promotion" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="LineDiscount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *                             &lt;element name="LineTotal" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Order", propOrder =
{ "code", "market", "status", "currency", "channel", "customer", "agentID", "storeID", "date", "gift", "delivery", "collectionPoint", "collectionPointMobileNumber", "orderPromotions", "totalDiscount", "payments", "totalNet", "totalGross", "taxes", "billingAddress", "shippingAddress", "entries" })
public class Order
{

    @XmlElement(name = "Code", required = true)
    protected String code;

    @XmlElement(name = "Market", required = true)
    protected String market;

    @XmlElement(name = "Status", required = true)
    protected String status;

    @XmlElement(name = "Currency", required = true)
    protected String currency;

    @XmlElement(name = "Channel", required = true)
    protected String channel;

    @XmlElement(name = "Customer", required = true)
    protected Order.Customer customer;

    @XmlElement(name = "AgentID")
    protected String agentID;

    @XmlElement(name = "StoreID")
    protected String storeID;

    @XmlElement(name = "Date")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar date;

    @XmlElement(name = "Gift")
    protected Order.Gift gift;

    @XmlElement(name = "Delivery")
    protected Order.Delivery delivery;

    @XmlElement(name = "CollectionPoint")
    protected String collectionPoint;

    @XmlElement(name = "CollectionPointMobileNumber")
    protected String collectionPointMobileNumber;

    @XmlElement(name = "OrderPromotions")
    protected Order.OrderPromotions orderPromotions;

    @XmlElement(name = "TotalDiscount")
    protected double totalDiscount;

    @XmlElement(name = "Payments", required = true)
    protected Order.Payments payments;

    @XmlElement(name = "TotalNet")
    protected Double totalNet;

    @XmlElement(name = "TotalGross")
    protected Double totalGross;

    @XmlElement(name = "Taxes")
    protected Order.Taxes taxes;

    @XmlElement(name = "BillingAddress", required = true)
    protected AddressType billingAddress;

    @XmlElement(name = "ShippingAddress", required = true)
    protected ShippingAddressType shippingAddress;

    @XmlElement(name = "Entries", required = true)
    protected Order.Entries entries;

    /**
     * Gets the value of the code property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getCode()
    {
        return code;
    }

    /**
     * Sets the value of the code property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCode(final String value)
    {
        this.code = value;
    }

    /**
     * Gets the value of the market property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getMarket()
    {
        return market;
    }

    /**
     * Sets the value of the market property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setMarket(final String value)
    {
        this.market = value;
    }

    /**
     * Gets the value of the status property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getStatus()
    {
        return status;
    }

    /**
     * Sets the value of the status property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setStatus(final String value)
    {
        this.status = value;
    }

    /**
     * Gets the value of the currency property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getCurrency()
    {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCurrency(final String value)
    {
        this.currency = value;
    }

    /**
     * Gets the value of the channel property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getChannel()
    {
        return channel;
    }

    /**
     * Sets the value of the channel property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setChannel(final String value)
    {
        this.channel = value;
    }

    /**
     * Gets the value of the customer property.
     *
     * @return possible object is {@link Order.Customer }
     * 
     */
    public Order.Customer getCustomer()
    {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     *
     * @param value
     *            allowed object is {@link Order.Customer }
     * 
     */
    public void setCustomer(final Order.Customer value)
    {
        this.customer = value;
    }

    /**
     * Gets the value of the agentID property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getAgentID()
    {
        return agentID;
    }

    /**
     * Sets the value of the agentID property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAgentID(final String value)
    {
        this.agentID = value;
    }

    /**
     * Gets the value of the storeID property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getStoreID()
    {
        return storeID;
    }

    /**
     * Sets the value of the storeID property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setStoreID(final String value)
    {
        this.storeID = value;
    }

    /**
     * Gets the value of the date property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDate()
    {
        return date;
    }

    /**
     * Sets the value of the date property.
     *
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setDate(final XMLGregorianCalendar value)
    {
        this.date = value;
    }

    /**
     * Gets the value of the gift property.
     *
     * @return possible object is {@link Order.Gift }
     * 
     */
    public Order.Gift getGift()
    {
        return gift;
    }

    /**
     * Sets the value of the gift property.
     *
     * @param value
     *            allowed object is {@link Order.Gift }
     * 
     */
    public void setGift(final Order.Gift value)
    {
        this.gift = value;
    }

    /**
     * Gets the value of the delivery property.
     *
     * @return possible object is {@link Order.Delivery }
     * 
     */
    public Order.Delivery getDelivery()
    {
        return delivery;
    }

    /**
     * Sets the value of the delivery property.
     *
     * @param value
     *            allowed object is {@link Order.Delivery }
     * 
     */
    public void setDelivery(final Order.Delivery value)
    {
        this.delivery = value;
    }

    /**
     * Gets the value of the collectionPoint property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getCollectionPoint()
    {
        return collectionPoint;
    }

    /**
     * Sets the value of the collectionPoint property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCollectionPoint(final String value)
    {
        this.collectionPoint = value;
    }

    /**
     * Gets the value of the collectionPointMobileNumber property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getCollectionPointMobileNumber()
    {
        return collectionPointMobileNumber;
    }

    /**
     * Sets the value of the collectionPointMobileNumber property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCollectionPointMobileNumber(final String value)
    {
        this.collectionPointMobileNumber = value;
    }

    /**
     * Gets the value of the orderPromotions property.
     *
     * @return possible object is {@link Order.OrderPromotions }
     * 
     */
    public Order.OrderPromotions getOrderPromotions()
    {
        return orderPromotions;
    }

    /**
     * Sets the value of the orderPromotions property.
     *
     * @param value
     *            allowed object is {@link Order.OrderPromotions }
     * 
     */
    public void setOrderPromotions(final Order.OrderPromotions value)
    {
        this.orderPromotions = value;
    }

    /**
     * Gets the value of the totalDiscount property.
     *
     */
    public double getTotalDiscount()
    {
        return totalDiscount;
    }

    /**
     * Sets the value of the totalDiscount property.
     *
     */
    public void setTotalDiscount(final double value)
    {
        this.totalDiscount = value;
    }

    /**
     * Gets the value of the payments property.
     *
     * @return possible object is {@link Order.Payments }
     * 
     */
    public Order.Payments getPayments()
    {
        return payments;
    }

    /**
     * Sets the value of the payments property.
     *
     * @param value
     *            allowed object is {@link Order.Payments }
     * 
     */
    public void setPayments(final Order.Payments value)
    {
        this.payments = value;
    }

    /**
     * Gets the value of the totalNet property.
     *
     * @return possible object is {@link Double }
     * 
     */
    public Double getTotalNet()
    {
        return totalNet;
    }

    /**
     * Sets the value of the totalNet property.
     *
     * @param value
     *            allowed object is {@link Double }
     * 
     */
    public void setTotalNet(final Double value)
    {
        this.totalNet = value;
    }

    /**
     * Gets the value of the totalGross property.
     *
     * @return possible object is {@link Double }
     * 
     */
    public Double getTotalGross()
    {
        return totalGross;
    }

    /**
     * Sets the value of the totalGross property.
     *
     * @param value
     *            allowed object is {@link Double }
     * 
     */
    public void setTotalGross(final Double value)
    {
        this.totalGross = value;
    }

    /**
     * Gets the value of the taxes property.
     *
     * @return possible object is {@link Order.Taxes }
     * 
     */
    public Order.Taxes getTaxes()
    {
        return taxes;
    }

    /**
     * Sets the value of the taxes property.
     *
     * @param value
     *            allowed object is {@link Order.Taxes }
     * 
     */
    public void setTaxes(final Order.Taxes value)
    {
        this.taxes = value;
    }

    /**
     * Gets the value of the billingAddress property.
     *
     * @return possible object is {@link AddressType }
     * 
     */
    public AddressType getBillingAddress()
    {
        return billingAddress;
    }

    /**
     * Sets the value of the billingAddress property.
     *
     * @param value
     *            allowed object is {@link AddressType }
     * 
     */
    public void setBillingAddress(final AddressType value)
    {
        this.billingAddress = value;
    }

    /**
     * Gets the value of the shippingAddress property.
     *
     * @return possible object is {@link ShippingAddressType }
     * 
     */
    public ShippingAddressType getShippingAddress()
    {
        return shippingAddress;
    }

    /**
     * Sets the value of the shippingAddress property.
     *
     * @param value
     *            allowed object is {@link ShippingAddressType }
     * 
     */
    public void setShippingAddress(final ShippingAddressType value)
    {
        this.shippingAddress = value;
    }

    /**
     * Gets the value of the entries property.
     *
     * @return possible object is {@link Order.Entries }
     * 
     */
    public Order.Entries getEntries()
    {
        return entries;
    }

    /**
     * Sets the value of the entries property.
     *
     * @param value
     *            allowed object is {@link Order.Entries }
     * 
     */
    public void setEntries(final Order.Entries value)
    {
        this.entries = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CustomerID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="LoyaltyCardNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="EmailAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Gender" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="CompanyName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder =
    { "customerID", "loyaltyCardNumber", "emailAddress", "gender", "companyName" })
    public static class Customer
    {

        @XmlElement(name = "CustomerID", required = true)
        protected String customerID;

        @XmlElement(name = "LoyaltyCardNumber")
        protected String loyaltyCardNumber;

        @XmlElement(name = "EmailAddress", required = true)
        protected String emailAddress;

        @XmlElement(name = "Gender")
        protected String gender;

        @XmlElement(name = "CompanyName")
        protected String companyName;

        /**
         * Gets the value of the customerID property.
         *
         * @return possible object is {@link String }
         * 
         */
        public String getCustomerID()
        {
            return customerID;
        }

        /**
         * Sets the value of the customerID property.
         *
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setCustomerID(final String value)
        {
            this.customerID = value;
        }

        /**
         * Gets the value of the loyaltyCardNumber property.
         *
         * @return possible object is {@link String }
         * 
         */
        public String getLoyaltyCardNumber()
        {
            return loyaltyCardNumber;
        }

        /**
         * Sets the value of the loyaltyCardNumber property.
         *
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setLoyaltyCardNumber(final String value)
        {
            this.loyaltyCardNumber = value;
        }

        /**
         * Gets the value of the emailAddress property.
         *
         * @return possible object is {@link String }
         * 
         */
        public String getEmailAddress()
        {
            return emailAddress;
        }

        /**
         * Sets the value of the emailAddress property.
         *
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setEmailAddress(final String value)
        {
            this.emailAddress = value;
        }

        /**
         * Gets the value of the gender property.
         *
         * @return possible object is {@link String }
         * 
         */
        public String getGender()
        {
            return gender;
        }

        /**
         * Sets the value of the gender property.
         *
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setGender(final String value)
        {
            this.gender = value;
        }

        /**
         * Gets the value of the companyName property.
         *
         * @return possible object is {@link String }
         * 
         */
        public String getCompanyName()
        {
            return companyName;
        }

        /**
         * Sets the value of the companyName property.
         *
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setCompanyName(final String value)
        {
            this.companyName = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DeliveryMethod" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DeliveryCost" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="DeliverySpecialInstructions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="DiscountPromotionCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="DiscountValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Refunded" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder =
    { "deliveryMethod", "deliveryCost", "deliverySpecialInstructions", "discountPromotionCode", "discountValue", "refunded" })
    public static class Delivery
    {

        @XmlElement(name = "DeliveryMethod", required = true)
        protected String deliveryMethod;

        @XmlElement(name = "DeliveryCost")
        protected double deliveryCost;

        @XmlElement(name = "DeliverySpecialInstructions")
        protected String deliverySpecialInstructions;

        @XmlElement(name = "DiscountPromotionCode")
        protected String discountPromotionCode;

        @XmlElement(name = "DiscountValue")
        protected String discountValue;

        @XmlElement(name = "Refunded")
        protected Boolean refunded;

        /**
         * Gets the value of the deliveryMethod property.
         *
         * @return possible object is {@link String }
         * 
         */
        public String getDeliveryMethod()
        {
            return deliveryMethod;
        }

        /**
         * Sets the value of the deliveryMethod property.
         *
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setDeliveryMethod(final String value)
        {
            this.deliveryMethod = value;
        }

        /**
         * Gets the value of the deliveryCost property.
         *
         */
        public double getDeliveryCost()
        {
            return deliveryCost;
        }

        /**
         * Sets the value of the deliveryCost property.
         *
         */
        public void setDeliveryCost(final double value)
        {
            this.deliveryCost = value;
        }

        /**
         * Gets the value of the deliverySpecialInstructions property.
         *
         * @return possible object is {@link String }
         * 
         */
        public String getDeliverySpecialInstructions()
        {
            return deliverySpecialInstructions;
        }

        /**
         * Sets the value of the deliverySpecialInstructions property.
         *
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setDeliverySpecialInstructions(final String value)
        {
            this.deliverySpecialInstructions = value;
        }

        /**
         * Gets the value of the discountPromotionCode property.
         *
         * @return possible object is {@link String }
         * 
         */
        public String getDiscountPromotionCode()
        {
            return discountPromotionCode;
        }

        /**
         * Sets the value of the discountPromotionCode property.
         *
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setDiscountPromotionCode(final String value)
        {
            this.discountPromotionCode = value;
        }

        /**
         * Gets the value of the discountValue property.
         *
         * @return possible object is {@link String }
         * 
         */
        public String getDiscountValue()
        {
            return discountValue;
        }

        /**
         * Sets the value of the discountValue property.
         *
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setDiscountValue(final String value)
        {
            this.discountValue = value;
        }

        /**
         * Gets the value of the refunded property.
         *
         * @return possible object is {@link Boolean }
         * 
         */
        public Boolean isRefunded()
        {
            return refunded;
        }

        /**
         * Sets the value of the refunded property.
         *
         * @param value
         *            allowed object is {@link Boolean }
         * 
         */
        public void setRefunded(final Boolean value)
        {
            this.refunded = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Entry" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="EntryNumber">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                         &lt;maxLength value="5"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ArticleId">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                         &lt;maxLength value="18"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="ReturnedQuantity" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                   &lt;element name="GiftWrapped" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="Unit" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="UnitPrice" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                   &lt;element name="LinePromotions" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Promotion" type="{http://thebodyshop/orderFetchSchema}Promotion" maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="LineDiscount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
     *                   &lt;element name="LineTotal" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder =
    { "entry" })
    public static class Entries
    {

        @XmlElement(name = "Entry", required = true)
        protected List<Order.Entries.Entry> entry;

        /**
         * Gets the value of the entry property.
         *
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the entry
         * property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getEntry().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list {@link Order.Entries.Entry }
         *
         *
         */
        public List<Order.Entries.Entry> getEntry()
        {
            if (entry == null)
            {
                entry = new ArrayList<Order.Entries.Entry>();
            }
            return this.entry;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         *
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="EntryNumber">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *               &lt;maxLength value="5"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ArticleId">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *               &lt;maxLength value="18"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="ReturnedQuantity" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *         &lt;element name="GiftWrapped" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="Unit" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="UnitPrice" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *         &lt;element name="LinePromotions" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Promotion" type="{http://thebodyshop/orderFetchSchema}Promotion" maxOccurs="unbounded" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="LineDiscount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
         *         &lt;element name="LineTotal" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder =
        { "entryNumber", "status", "articleId", "quantity", "returnedQuantity", "giftWrapped", "unit", "unitPrice", "linePromotions", "lineDiscount", "lineTotal" })
        public static class Entry
        {

            @XmlElement(name = "EntryNumber", required = true)
            protected String entryNumber;

            @XmlElement(name = "Status", required = true)
            protected String status;

            @XmlElement(name = "ArticleId", required = true)
            protected String articleId;

            @XmlElement(name = "Quantity")
            protected int quantity;

            @XmlElement(name = "ReturnedQuantity")
            protected Integer returnedQuantity;

            @XmlElement(name = "GiftWrapped")
            protected boolean giftWrapped;

            @XmlElement(name = "Unit", required = true)
            protected String unit;

            @XmlElement(name = "UnitPrice")
            protected double unitPrice;

            @XmlElement(name = "LinePromotions")
            protected Order.Entries.Entry.LinePromotions linePromotions;

            @XmlElement(name = "LineDiscount")
            protected Double lineDiscount;

            @XmlElement(name = "LineTotal")
            protected Double lineTotal;

            /**
             * Gets the value of the entryNumber property.
             *
             * @return possible object is {@link String }
             * 
             */
            public String getEntryNumber()
            {
                return entryNumber;
            }

            /**
             * Sets the value of the entryNumber property.
             *
             * @param value
             *            allowed object is {@link String }
             * 
             */
            public void setEntryNumber(final String value)
            {
                this.entryNumber = value;
            }

            /**
             * Gets the value of the status property.
             *
             * @return possible object is {@link String }
             * 
             */
            public String getStatus()
            {
                return status;
            }

            /**
             * Sets the value of the status property.
             *
             * @param value
             *            allowed object is {@link String }
             * 
             */
            public void setStatus(final String value)
            {
                this.status = value;
            }

            /**
             * Gets the value of the articleId property.
             *
             * @return possible object is {@link String }
             * 
             */
            public String getArticleId()
            {
                return articleId;
            }

            /**
             * Sets the value of the articleId property.
             *
             * @param value
             *            allowed object is {@link String }
             * 
             */
            public void setArticleId(final String value)
            {
                this.articleId = value;
            }

            /**
             * Gets the value of the quantity property.
             *
             */
            public int getQuantity()
            {
                return quantity;
            }

            /**
             * Sets the value of the quantity property.
             *
             */
            public void setQuantity(final int value)
            {
                this.quantity = value;
            }

            /**
             * Gets the value of the returnedQuantity property.
             *
             * @return possible object is {@link Integer }
             * 
             */
            public Integer getReturnedQuantity()
            {
                return returnedQuantity;
            }

            /**
             * Sets the value of the returnedQuantity property.
             *
             * @param value
             *            allowed object is {@link Integer }
             * 
             */
            public void setReturnedQuantity(final Integer value)
            {
                this.returnedQuantity = value;
            }

            /**
             * Gets the value of the giftWrapped property.
             *
             */
            public boolean isGiftWrapped()
            {
                return giftWrapped;
            }

            /**
             * Sets the value of the giftWrapped property.
             *
             */
            public void setGiftWrapped(final boolean value)
            {
                this.giftWrapped = value;
            }

            /**
             * Gets the value of the unit property.
             *
             * @return possible object is {@link String }
             * 
             */
            public String getUnit()
            {
                return unit;
            }

            /**
             * Sets the value of the unit property.
             *
             * @param value
             *            allowed object is {@link String }
             * 
             */
            public void setUnit(final String value)
            {
                this.unit = value;
            }

            /**
             * Gets the value of the unitPrice property.
             *
             */
            public double getUnitPrice()
            {
                return unitPrice;
            }

            /**
             * Sets the value of the unitPrice property.
             *
             */
            public void setUnitPrice(final double value)
            {
                this.unitPrice = value;
            }

            /**
             * Gets the value of the linePromotions property.
             *
             * @return possible object is {@link Order.Entries.Entry.LinePromotions }
             * 
             */
            public Order.Entries.Entry.LinePromotions getLinePromotions()
            {
                return linePromotions;
            }

            /**
             * Sets the value of the linePromotions property.
             *
             * @param value
             *            allowed object is {@link Order.Entries.Entry.LinePromotions }
             * 
             */
            public void setLinePromotions(final Order.Entries.Entry.LinePromotions value)
            {
                this.linePromotions = value;
            }

            /**
             * Gets the value of the lineDiscount property.
             *
             * @return possible object is {@link Double }
             * 
             */
            public Double getLineDiscount()
            {
                return lineDiscount;
            }

            /**
             * Sets the value of the lineDiscount property.
             *
             * @param value
             *            allowed object is {@link Double }
             * 
             */
            public void setLineDiscount(final Double value)
            {
                this.lineDiscount = value;
            }

            /**
             * Gets the value of the lineTotal property.
             *
             * @return possible object is {@link Double }
             * 
             */
            public Double getLineTotal()
            {
                return lineTotal;
            }

            /**
             * Sets the value of the lineTotal property.
             *
             * @param value
             *            allowed object is {@link Double }
             * 
             */
            public void setLineTotal(final Double value)
            {
                this.lineTotal = value;
            }

            /**
             * <p>
             * Java class for anonymous complex type.
             *
             * <p>
             * The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Promotion" type="{http://thebodyshop/orderFetchSchema}Promotion" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder =
            { "promotion" })
            public static class LinePromotions
            {

                @XmlElement(name = "Promotion")
                protected List<Promotion> promotion;

                /**
                 * Gets the value of the promotion property.
                 *
                 * <p>
                 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the
                 * promotion property.
                 *
                 * <p>
                 * For example, to add a new item, do as follows:
                 * 
                 * <pre>
                 * getPromotion().add(newItem);
                 * </pre>
                 *
                 *
                 * <p>
                 * Objects of the following type(s) are allowed in the list {@link Promotion }
                 *
                 *
                 */
                public List<Promotion> getPromotion()
                {
                    if (promotion == null)
                    {
                        promotion = new ArrayList<Promotion>();
                    }
                    return this.promotion;
                }

            }

        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="From" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="To" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Cost" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder =
    { "from", "to", "message", "cost" })
    public static class Gift
    {

        @XmlElement(name = "From")
        protected String from;

        @XmlElement(name = "To")
        protected String to;

        @XmlElement(name = "Message")
        protected String message;

        @XmlElement(name = "Cost")
        protected Double cost;

        /**
         * Gets the value of the from property.
         *
         * @return possible object is {@link String }
         * 
         */
        public String getFrom()
        {
            return from;
        }

        /**
         * Sets the value of the from property.
         *
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setFrom(final String value)
        {
            this.from = value;
        }

        /**
         * Gets the value of the to property.
         *
         * @return possible object is {@link String }
         * 
         */
        public String getTo()
        {
            return to;
        }

        /**
         * Sets the value of the to property.
         *
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setTo(final String value)
        {
            this.to = value;
        }

        /**
         * Gets the value of the message property.
         *
         * @return possible object is {@link String }
         * 
         */
        public String getMessage()
        {
            return message;
        }

        /**
         * Sets the value of the message property.
         *
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setMessage(final String value)
        {
            this.message = value;
        }

        /**
         * Gets the value of the cost property.
         *
         * @return possible object is {@link Double }
         * 
         */
        public Double getCost()
        {
            return cost;
        }

        /**
         * Sets the value of the cost property.
         *
         * @param value
         *            allowed object is {@link Double }
         * 
         */
        public void setCost(final Double value)
        {
            this.cost = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder =
    { "code" })
    public static class OrderPromotions
    {

        @XmlElement(name = "Code")
        protected List<String> code;

        /**
         * Gets the value of the code property.
         *
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the code
         * property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getCode().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list {@link String }
         *
         *
         */
        public List<String> getCode()
        {
            if (code == null)
            {
                code = new ArrayList<String>();
            }
            return this.code;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Payment" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                   &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="TransactionDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder =
    { "payment" })
    public static class Payments
    {

        @XmlElement(name = "Payment")
        protected List<Order.Payments.Payment> payment;

        /**
         * Gets the value of the payment property.
         *
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the payment
         * property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getPayment().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list {@link Order.Payments.Payment }
         *
         *
         */
        public List<Order.Payments.Payment> getPayment()
        {
            if (payment == null)
            {
                payment = new ArrayList<Order.Payments.Payment>();
            }
            return this.payment;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         *
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="TransactionDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder =
        { "id", "type", "amount", "status", "transactionDate" })
        public static class Payment
        {

            @XmlElement(name = "ID", required = true)
            protected String id;

            @XmlElement(name = "Type", required = true)
            protected String type;

            @XmlElement(name = "Amount")
            protected double amount;

            @XmlElement(name = "Status", required = true)
            protected String status;

            @XmlElement(name = "TransactionDate", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar transactionDate;

            /**
             * Gets the value of the id property.
             *
             * @return possible object is {@link String }
             * 
             */
            public String getID()
            {
                return id;
            }

            /**
             * Sets the value of the id property.
             *
             * @param value
             *            allowed object is {@link String }
             * 
             */
            public void setID(final String value)
            {
                this.id = value;
            }

            /**
             * Gets the value of the type property.
             *
             * @return possible object is {@link String }
             * 
             */
            public String getType()
            {
                return type;
            }

            /**
             * Sets the value of the type property.
             *
             * @param value
             *            allowed object is {@link String }
             * 
             */
            public void setType(final String value)
            {
                this.type = value;
            }

            /**
             * Gets the value of the amount property.
             *
             */
            public double getAmount()
            {
                return amount;
            }

            /**
             * Sets the value of the amount property.
             *
             */
            public void setAmount(final double value)
            {
                this.amount = value;
            }

            /**
             * Gets the value of the status property.
             *
             * @return possible object is {@link String }
             * 
             */
            public String getStatus()
            {
                return status;
            }

            /**
             * Sets the value of the status property.
             *
             * @param value
             *            allowed object is {@link String }
             * 
             */
            public void setStatus(final String value)
            {
                this.status = value;
            }

            /**
             * Gets the value of the transactionDate property.
             *
             * @return possible object is {@link XMLGregorianCalendar }
             * 
             */
            public XMLGregorianCalendar getTransactionDate()
            {
                return transactionDate;
            }

            /**
             * Sets the value of the transactionDate property.
             *
             * @param value
             *            allowed object is {@link XMLGregorianCalendar }
             * 
             */
            public void setTransactionDate(final XMLGregorianCalendar value)
            {
                this.transactionDate = value;
            }

        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Tax" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>double">
     *                 &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder =
    { "tax" })
    public static class Taxes
    {

        @XmlElement(name = "Tax")
        protected List<Order.Taxes.Tax> tax;

        /**
         * Gets the value of the tax property.
         *
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the tax
         * property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getTax().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list {@link Order.Taxes.Tax }
         *
         *
         */
        public List<Order.Taxes.Tax> getTax()
        {
            if (tax == null)
            {
                tax = new ArrayList<Order.Taxes.Tax>();
            }
            return this.tax;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         *
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>double">
         *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder =
        { "value" })
        public static class Tax
        {

            @XmlValue
            protected double value;

            @XmlAttribute(name = "code")
            protected String code;

            /**
             * Gets the value of the value property.
             *
             */
            public double getValue()
            {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             */
            public void setValue(final double value)
            {
                this.value = value;
            }

            /**
             * Gets the value of the code property.
             *
             * @return possible object is {@link String }
             * 
             */
            public String getCode()
            {
                return code;
            }

            /**
             * Sets the value of the code property.
             *
             * @param value
             *            allowed object is {@link String }
             * 
             */
            public void setCode(final String value)
            {
                this.code = value;
            }

        }

    }

}
