//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.11.07 at 02:29:28 PM GMT
//

package uk.co.thebodyshop.integration.jaxb.store.order.fetch;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ShippingAddressType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ShippingAddressType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://thebodyshop/orderFetchSchema}AddressType">
 *       &lt;sequence>
 *         &lt;element name="EmailAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SMSNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShippingAddressType", propOrder =
{ "emailAddress", "smsNumber", "phoneNumber" })
public class ShippingAddressType extends AddressType
{

    @XmlElement(name = "EmailAddress")
    protected String emailAddress;

    @XmlElement(name = "SMSNumber")
    protected String smsNumber;

    @XmlElement(name = "PhoneNumber")
    protected String phoneNumber;

    /**
     * Gets the value of the emailAddress property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getEmailAddress()
    {
        return emailAddress;
    }

    /**
     * Sets the value of the emailAddress property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setEmailAddress(final String value)
    {
        this.emailAddress = value;
    }

    /**
     * Gets the value of the smsNumber property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getSMSNumber()
    {
        return smsNumber;
    }

    /**
     * Sets the value of the smsNumber property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSMSNumber(final String value)
    {
        this.smsNumber = value;
    }

    /**
     * Gets the value of the phoneNumber property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getPhoneNumber()
    {
        return phoneNumber;
    }

    /**
     * Sets the value of the phoneNumber property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPhoneNumber(final String value)
    {
        this.phoneNumber = value;
    }

}
