//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.06.09 at 09:48:12 PM BST
//

package uk.co.thebodyshop.integration.jaxb.product;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for Product complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Product">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ArticleId">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="18"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Type">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://thebodyshop/productSchema}ProductTypeEnum">
 *               &lt;pattern value="[A-Z]{4}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Name" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="lang" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Description" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="lang" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Ean">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="18"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Gtin">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="18"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PlanArticle">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BrandCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BrandDescription" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="lang" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="FormatCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FormatDescription" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="lang" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Hazardous" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="HazardousClass" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Category" type="{http://thebodyshop/productSchema}Category" maxOccurs="unbounded"/>
 *         &lt;element name="UnitCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="UnitValue" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *               &lt;maxInclusive value="9999999999999"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MllVariant" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ArticleLifecycleCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ArticleLifecycleDescription" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="lang" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Product", propOrder =
{ "articleId", "type", "name", "description", "ean", "gtin", "planArticle", "brandCode", "brandDescription", "formatCode", "formatDescription", "hazardous", "hazardousClass", "category", "unitCode", "unitValue", "mllVariant", "articleLifecycleCode", "articleLifecycleDescription" })
@XmlRootElement(name = "Product")
public class Product
{

    @XmlElement(name = "ArticleId", required = true)
    protected String articleId;

    @XmlElement(name = "Type", required = true)
    protected ProductTypeEnum type;

    @XmlElement(name = "Name", required = true)
    protected List<Product.Name> name;

    @XmlElement(name = "Description", required = true)
    protected List<Product.Description> description;

    @XmlElement(name = "Ean", required = true)
    protected String ean;

    @XmlElement(name = "Gtin", required = true)
    protected String gtin;

    @XmlElement(name = "PlanArticle", required = true)
    protected String planArticle;

    @XmlElement(name = "BrandCode")
    protected String brandCode;

    @XmlElement(name = "BrandDescription")
    protected List<Product.BrandDescription> brandDescription;

    @XmlElement(name = "FormatCode")
    protected String formatCode;

    @XmlElement(name = "FormatDescription")
    protected List<Product.FormatDescription> formatDescription;

    @XmlElement(name = "Hazardous", defaultValue = "false")
    protected Boolean hazardous;

    @XmlElement(name = "HazardousClass")
    protected String hazardousClass;

    @XmlElement(name = "Category", required = true)
    protected List<Category> category;

    @XmlElement(name = "UnitCode")
    protected String unitCode;

    @XmlElement(name = "UnitValue", defaultValue = "0.00")
    protected Double unitValue;

    @XmlElement(name = "MllVariant")
    protected String mllVariant;

    @XmlElement(name = "ArticleLifecycleCode")
    protected String articleLifecycleCode;

    @XmlElement(name = "ArticleLifecycleDescription")
    protected List<Product.ArticleLifecycleDescription> articleLifecycleDescription;

    /**
     * Gets the value of the articleId property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getArticleId()
    {
        return articleId;
    }

    /**
     * Sets the value of the articleId property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setArticleId(final String value)
    {
        this.articleId = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is {@link ProductTypeEnum }
     * 
     */
    public ProductTypeEnum getType()
    {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value
     *            allowed object is {@link ProductTypeEnum }
     * 
     */
    public void setType(final ProductTypeEnum value)
    {
        this.type = value;
    }

    /**
     * Gets the value of the name property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the name
     * property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getName().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Product.Name }
     *
     *
     */
    public List<Product.Name> getName()
    {
        if (name == null)
        {
            name = new ArrayList<Product.Name>();
        }
        return this.name;
    }

    /**
     * Gets the value of the description property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the description
     * property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getDescription().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Product.Description }
     *
     *
     */
    public List<Product.Description> getDescription()
    {
        if (description == null)
        {
            description = new ArrayList<Product.Description>();
        }
        return this.description;
    }

    /**
     * Gets the value of the ean property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getEan()
    {
        return ean;
    }

    /**
     * Sets the value of the ean property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setEan(final String value)
    {
        this.ean = value;
    }

    /**
     * Gets the value of the gtin property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getGtin()
    {
        return gtin;
    }

    /**
     * Sets the value of the gtin property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setGtin(final String value)
    {
        this.gtin = value;
    }

    /**
     * Gets the value of the planArticle property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getPlanArticle()
    {
        return planArticle;
    }

    /**
     * Sets the value of the planArticle property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPlanArticle(final String value)
    {
        this.planArticle = value;
    }

    /**
     * Gets the value of the brandCode property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getBrandCode()
    {
        return brandCode;
    }

    /**
     * Sets the value of the brandCode property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setBrandCode(final String value)
    {
        this.brandCode = value;
    }

    /**
     * Gets the value of the brandDescription property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the
     * brandDescription property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getBrandDescription().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Product.BrandDescription }
     *
     *
     */
    public List<Product.BrandDescription> getBrandDescription()
    {
        if (brandDescription == null)
        {
            brandDescription = new ArrayList<Product.BrandDescription>();
        }
        return this.brandDescription;
    }

    /**
     * Gets the value of the formatCode property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getFormatCode()
    {
        return formatCode;
    }

    /**
     * Sets the value of the formatCode property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFormatCode(final String value)
    {
        this.formatCode = value;
    }

    /**
     * Gets the value of the formatDescription property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the
     * formatDescription property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getFormatDescription().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Product.FormatDescription }
     *
     *
     */
    public List<Product.FormatDescription> getFormatDescription()
    {
        if (formatDescription == null)
        {
            formatDescription = new ArrayList<Product.FormatDescription>();
        }
        return this.formatDescription;
    }

    /**
     * Gets the value of the hazardous property.
     *
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isHazardous()
    {
        return hazardous;
    }

    /**
     * Sets the value of the hazardous property.
     *
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setHazardous(final Boolean value)
    {
        this.hazardous = value;
    }

    /**
     * Gets the value of the hazardousClass property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getHazardousClass()
    {
        return hazardousClass;
    }

    /**
     * Sets the value of the hazardousClass property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setHazardousClass(final String value)
    {
        this.hazardousClass = value;
    }

    /**
     * Gets the value of the category property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the category
     * property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getCategory().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Category }
     *
     *
     */
    public List<Category> getCategory()
    {
        if (category == null)
        {
            category = new ArrayList<Category>();
        }
        return this.category;
    }

    /**
     * Gets the value of the unitCode property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getUnitCode()
    {
        return unitCode;
    }

    /**
     * Sets the value of the unitCode property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setUnitCode(final String value)
    {
        this.unitCode = value;
    }

    /**
     * Gets the value of the unitValue property.
     *
     * @return possible object is {@link Double }
     * 
     */
    public Double getUnitValue()
    {
        return unitValue;
    }

    /**
     * Sets the value of the unitValue property.
     *
     * @param value
     *            allowed object is {@link Double }
     * 
     */
    public void setUnitValue(final Double value)
    {
        this.unitValue = value;
    }

    /**
     * Gets the value of the mllVariant property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getMllVariant()
    {
        return mllVariant;
    }

    /**
     * Sets the value of the mllVariant property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setMllVariant(final String value)
    {
        this.mllVariant = value;
    }

    /**
     * Gets the value of the articleLifecycleCode property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getArticleLifecycleCode()
    {
        return articleLifecycleCode;
    }

    /**
     * Sets the value of the articleLifecycleCode property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setArticleLifecycleCode(final String value)
    {
        this.articleLifecycleCode = value;
    }

    /**
     * Gets the value of the articleLifecycleDescription property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the
     * articleLifecycleDescription property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getArticleLifecycleDescription().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Product.ArticleLifecycleDescription }
     *
     *
     */
    public List<Product.ArticleLifecycleDescription> getArticleLifecycleDescription()
    {
        if (articleLifecycleDescription == null)
        {
            articleLifecycleDescription = new ArrayList<Product.ArticleLifecycleDescription>();
        }
        return this.articleLifecycleDescription;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="lang" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder =
    { "value" })
    public static class ArticleLifecycleDescription
    {

        @XmlValue
        protected String value;

        @XmlAttribute(name = "lang", required = true)
        protected String lang;

        /**
         * Gets the value of the value property.
         *
         * @return possible object is {@link String }
         * 
         */
        public String getValue()
        {
            return value;
        }

        /**
         * Sets the value of the value property.
         *
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setValue(final String value)
        {
            this.value = value;
        }

        /**
         * Gets the value of the lang property.
         *
         * @return possible object is {@link String }
         * 
         */
        public String getLang()
        {
            return lang;
        }

        /**
         * Sets the value of the lang property.
         *
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setLang(final String value)
        {
            this.lang = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="lang" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder =
    { "value" })
    public static class BrandDescription
    {

        @XmlValue
        protected String value;

        @XmlAttribute(name = "lang", required = true)
        protected String lang;

        /**
         * Gets the value of the value property.
         *
         * @return possible object is {@link String }
         * 
         */
        public String getValue()
        {
            return value;
        }

        /**
         * Sets the value of the value property.
         *
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setValue(final String value)
        {
            this.value = value;
        }

        /**
         * Gets the value of the lang property.
         *
         * @return possible object is {@link String }
         * 
         */
        public String getLang()
        {
            return lang;
        }

        /**
         * Sets the value of the lang property.
         *
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setLang(final String value)
        {
            this.lang = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="lang" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder =
    { "value" })
    public static class Description
    {

        @XmlValue
        protected String value;

        @XmlAttribute(name = "lang", required = true)
        protected String lang;

        /**
         * Gets the value of the value property.
         *
         * @return possible object is {@link String }
         * 
         */
        public String getValue()
        {
            return value;
        }

        /**
         * Sets the value of the value property.
         *
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setValue(final String value)
        {
            this.value = value;
        }

        /**
         * Gets the value of the lang property.
         *
         * @return possible object is {@link String }
         * 
         */
        public String getLang()
        {
            return lang;
        }

        /**
         * Sets the value of the lang property.
         *
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setLang(final String value)
        {
            this.lang = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="lang" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder =
    { "value" })
    public static class FormatDescription
    {

        @XmlValue
        protected String value;

        @XmlAttribute(name = "lang", required = true)
        protected String lang;

        /**
         * Gets the value of the value property.
         *
         * @return possible object is {@link String }
         * 
         */
        public String getValue()
        {
            return value;
        }

        /**
         * Sets the value of the value property.
         *
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setValue(final String value)
        {
            this.value = value;
        }

        /**
         * Gets the value of the lang property.
         *
         * @return possible object is {@link String }
         * 
         */
        public String getLang()
        {
            return lang;
        }

        /**
         * Sets the value of the lang property.
         *
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setLang(final String value)
        {
            this.lang = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="lang" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder =
    { "value" })
    public static class Name
    {

        @XmlValue
        protected String value;

        @XmlAttribute(name = "lang", required = true)
        protected String lang;

        /**
         * Gets the value of the value property.
         *
         * @return possible object is {@link String }
         * 
         */
        public String getValue()
        {
            return value;
        }

        /**
         * Sets the value of the value property.
         *
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setValue(final String value)
        {
            this.value = value;
        }

        /**
         * Gets the value of the lang property.
         *
         * @return possible object is {@link String }
         * 
         */
        public String getLang()
        {
            return lang;
        }

        /**
         * Sets the value of the lang property.
         *
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setLang(final String value)
        {
            this.lang = value;
        }

    }

}
