//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.06.09 at 09:20:35 PM BST
//

package uk.co.thebodyshop.integration.jaxb.price;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Price complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Price">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ArticleId">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="18"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Value">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;maxInclusive value="999999999999"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Currency">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[A-Z]{3}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Type" type="{http://thebodyshop/priceSchema}PriceTypeEnum"/>
 *         &lt;element name="Market" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Price", propOrder =
{ "articleId", "value", "currency", "type", "market" })
@XmlRootElement(name = "Price")
public class Price
{

    @XmlElement(name = "ArticleId", required = true)
    protected String articleId;

    @XmlElement(name = "Value", required = true)
    protected BigDecimal value;

    @XmlElement(name = "Currency", required = true)
    protected String currency;

    @XmlElement(name = "Type", required = true)
    protected PriceTypeEnum type;

    @XmlElement(name = "Market")
    protected String market;

    /**
     * Gets the value of the articleId property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getArticleId()
    {
        return articleId;
    }

    /**
     * Sets the value of the articleId property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setArticleId(final String value)
    {
        this.articleId = value;
    }

    /**
     * Gets the value of the value property.
     *
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getValue()
    {
        return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setValue(final BigDecimal value)
    {
        this.value = value;
    }

    /**
     * Gets the value of the currency property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getCurrency()
    {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCurrency(final String value)
    {
        this.currency = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is {@link PriceTypeEnum }
     * 
     */
    public PriceTypeEnum getType()
    {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value
     *            allowed object is {@link PriceTypeEnum }
     * 
     */
    public void setType(final PriceTypeEnum value)
    {
        this.type = value;
    }

    /**
     * Gets the value of the market property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getMarket()
    {
        return market;
    }

    /**
     * Sets the value of the market property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setMarket(final String value)
    {
        this.market = value;
    }

}
