//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.13 at 02:12:22 PM BST 
//


package uk.co.thebodyshop.integration.jaxb.store.benefit;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BenefitStatusEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BenefitStatusEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Available"/>
 *     &lt;enumeration value="Expired"/>
 *     &lt;enumeration value="Used"/>
 *     &lt;enumeration value="Donated"/>
 *     &lt;enumeration value="Authorised"/>
 *     &lt;enumeration value="Cancelled"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BenefitStatusEnum")
@XmlEnum
public enum BenefitStatusEnum {

    @XmlEnumValue("Available")
    AVAILABLE("Available"),
    @XmlEnumValue("Expired")
    EXPIRED("Expired"),
    @XmlEnumValue("Used")
    USED("Used"),
    @XmlEnumValue("Donated")
    DONATED("Donated"),
    @XmlEnumValue("Authorised")
    AUTHORISED("Authorised"),
    @XmlEnumValue("Cancelled")
    CANCELLED("Cancelled");
    private final String value;

    BenefitStatusEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BenefitStatusEnum fromValue(String v) {
        for (BenefitStatusEnum c: BenefitStatusEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
