//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.13 at 02:12:22 PM BST 
//


package uk.co.thebodyshop.integration.jaxb.store.benefit;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BenefitTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BenefitTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AbsoluteMonetary"/>
 *     &lt;enumeration value="Promotion"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BenefitTypeEnum")
@XmlEnum
public enum BenefitTypeEnum {

    @XmlEnumValue("AbsoluteMonetary")
    ABSOLUTE_MONETARY("AbsoluteMonetary"),
    @XmlEnumValue("Promotion")
    PROMOTION("Promotion");
    private final String value;

    BenefitTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BenefitTypeEnum fromValue(String v) {
        for (BenefitTypeEnum c: BenefitTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
