//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.04.13 at 02:12:22 PM BST
//

package uk.co.thebodyshop.integration.jaxb.store.benefit;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the uk.co.portaltech.tbs.dataprocessing.jaxb.store.benefit package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java representation of XML content can consist of schema derived interfaces and classes representing the binding of schema type
 * definitions, element declarations and model groups. Factory methods for each of these are provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory
{

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.co.portaltech.tbs.dataprocessing.jaxb.store.benefit
     *
     */
    public ObjectFactory()
    {
    }

    /**
     * Create an instance of {@link ResponseStatus }
     *
     */
    public ResponseStatus createResponseStatus()
    {
        return new ResponseStatus();
    }

    /**
     * ======= Create an instance of {@link ReverseAuthBenefitResponse }
     *
     */
    public ReverseAuthBenefitResponse createReverseAuthBenefitResponse()
    {
        return new ReverseAuthBenefitResponse();
    }

    /**
     * Create an instance of {@link AuthBenefitResponse }
     *
     */
    public AuthBenefitResponse createAuthBenefitResponse()
    {
        return new AuthBenefitResponse();
    }

    /**
     * Create an instance of {@link CaptureBenefitRequest }
     *
     */
    public CaptureBenefitRequest createCaptureBenefitRequest()
    {
        return new CaptureBenefitRequest();
    }

    /**
     * Create an instance of {@link AuthBenefitRequest }
     *
     */
    public AuthBenefitRequest createAuthBenefitRequest()
    {
        return new AuthBenefitRequest();
    }

    /**
     * Create an instance of {@link ReverseAuthBenefitRequest }
     *
     */
    public ReverseAuthBenefitRequest createReverseAuthBenefitRequest()
    {
        return new ReverseAuthBenefitRequest();
    }

    /**
     * Create an instance of {@link CaptureBenefitResponse }
     *
     */
    public CaptureBenefitResponse createCaptureBenefitResponse()
    {
        return new CaptureBenefitResponse();
    }

}
