//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.15 at 02:26:24 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://thebodyshop/customerRegistrationSchema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package uk.co.thebodyshop.integration.jaxb.store.customer.registration;
