//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.07.06 at 05:41:00 PM BST
//

package uk.co.thebodyshop.integration.jaxb.order.shipmentconfirmation;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for OrderShipmentConfirmation complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="OrderShipmentConfirmation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Status" type="{http://thebodyshop/orderShipmentConfirmationSchema}SAPStatusEnum"/>
 *         &lt;element name="StatusNotificationDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StatusNotificationTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ShippingDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ShippingTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Carrier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CarrierService" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TrackingID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Entries">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Entry" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="EntryNumber">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="5"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="ArticleId">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="18"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Gtin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="QuantityDispatched" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderShipmentConfirmation", propOrder =
{ "code", "status", "statusNotificationDate", "statusNotificationTime", "shippingDate", "shippingTime", "carrier", "carrierService", "trackingID", "entries" })
@XmlRootElement(name = "OrderShipmentConfirmation")
public class OrderShipmentConfirmation
{

    @XmlElement(name = "Code", required = true)
    protected String code;

    @XmlElement(name = "Status", required = true)
    protected SAPStatusEnum status;

    @XmlElement(name = "StatusNotificationDate", required = true)
    protected String statusNotificationDate;

    @XmlElement(name = "StatusNotificationTime", required = true)
    protected String statusNotificationTime;

    @XmlElement(name = "ShippingDate", required = true)
    protected String shippingDate;

    @XmlElement(name = "ShippingTime", required = true)
    protected String shippingTime;

    @XmlElement(name = "Carrier", required = true)
    protected String carrier;

    @XmlElement(name = "CarrierService")
    protected String carrierService;

    @XmlElement(name = "TrackingID", required = true)
    protected String trackingID;

    @XmlElement(name = "Entries", required = true)
    protected OrderShipmentConfirmation.Entries entries;

    /**
     * Gets the value of the code property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getCode()
    {
        return code;
    }

    /**
     * Sets the value of the code property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCode(final String value)
    {
        this.code = value;
    }

    /**
     * Gets the value of the status property.
     *
     * @return possible object is {@link SAPStatusEnum }
     * 
     */
    public SAPStatusEnum getStatus()
    {
        return status;
    }

    /**
     * Sets the value of the status property.
     *
     * @param value
     *            allowed object is {@link SAPStatusEnum }
     * 
     */
    public void setStatus(final SAPStatusEnum value)
    {
        this.status = value;
    }

    /**
     * Gets the value of the statusNotificationDate property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getStatusNotificationDate()
    {
        return statusNotificationDate;
    }

    /**
     * Sets the value of the statusNotificationDate property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setStatusNotificationDate(final String value)
    {
        this.statusNotificationDate = value;
    }

    /**
     * Gets the value of the statusNotificationTime property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getStatusNotificationTime()
    {
        return statusNotificationTime;
    }

    /**
     * Sets the value of the statusNotificationTime property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setStatusNotificationTime(final String value)
    {
        this.statusNotificationTime = value;
    }

    /**
     * Gets the value of the shippingDate property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getShippingDate()
    {
        return shippingDate;
    }

    /**
     * Sets the value of the shippingDate property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setShippingDate(final String value)
    {
        this.shippingDate = value;
    }

    /**
     * Gets the value of the shippingTime property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getShippingTime()
    {
        return shippingTime;
    }

    /**
     * Sets the value of the shippingTime property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setShippingTime(final String value)
    {
        this.shippingTime = value;
    }

    /**
     * Gets the value of the carrier property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getCarrier()
    {
        return carrier;
    }

    /**
     * Sets the value of the carrier property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCarrier(final String value)
    {
        this.carrier = value;
    }

    /**
     * Gets the value of the carrierService property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getCarrierService()
    {
        return carrierService;
    }

    /**
     * Sets the value of the carrierService property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCarrierService(final String value)
    {
        this.carrierService = value;
    }

    /**
     * Gets the value of the trackingID property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getTrackingID()
    {
        return trackingID;
    }

    /**
     * Sets the value of the trackingID property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTrackingID(final String value)
    {
        this.trackingID = value;
    }

    /**
     * Gets the value of the entries property.
     *
     * @return possible object is {@link OrderShipmentConfirmation.Entries }
     * 
     */
    public OrderShipmentConfirmation.Entries getEntries()
    {
        return entries;
    }

    /**
     * Sets the value of the entries property.
     *
     * @param value
     *            allowed object is {@link OrderShipmentConfirmation.Entries }
     * 
     */
    public void setEntries(final OrderShipmentConfirmation.Entries value)
    {
        this.entries = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Entry" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="EntryNumber">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                         &lt;maxLength value="5"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="ArticleId">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                         &lt;maxLength value="18"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Gtin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="QuantityDispatched" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder =
    { "entry" })
    public static class Entries
    {

        @XmlElement(name = "Entry", required = true)
        protected List<OrderShipmentConfirmation.Entries.Entry> entry;

        /**
         * Gets the value of the entry property.
         *
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the entry
         * property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getEntry().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list {@link OrderShipmentConfirmation.Entries.Entry }
         *
         *
         */
        public List<OrderShipmentConfirmation.Entries.Entry> getEntry()
        {
            if (entry == null)
            {
                entry = new ArrayList<OrderShipmentConfirmation.Entries.Entry>();
            }
            return this.entry;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         *
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="EntryNumber">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *               &lt;maxLength value="5"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="ArticleId">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *               &lt;maxLength value="18"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Gtin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="QuantityDispatched" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder =
        { "entryNumber", "articleId", "gtin", "quantityDispatched" })
        public static class Entry
        {

            @XmlElement(name = "EntryNumber", required = true)
            protected String entryNumber;

            @XmlElement(name = "ArticleId", required = true)
            protected String articleId;

            @XmlElement(name = "Gtin", namespace = "http://thebodyshop/orderShipmentConfirmationSchema")
            protected String gtin;

            @XmlElement(name = "QuantityDispatched")
            protected int quantityDispatched;

            /**
             * Gets the value of the entryNumber property.
             *
             * @return possible object is {@link String }
             * 
             */
            public String getEntryNumber()
            {
                return entryNumber;
            }

            /**
             * Sets the value of the entryNumber property.
             *
             * @param value
             *            allowed object is {@link String }
             * 
             */
            public void setEntryNumber(final String value)
            {
                this.entryNumber = value;
            }

            /**
             * Gets the value of the articleId property.
             *
             * @return possible object is {@link String }
             * 
             */
            public String getArticleId()
            {
                return articleId;
            }

            /**
             * Sets the value of the articleId property.
             *
             * @param value
             *            allowed object is {@link String }
             * 
             */
            public void setArticleId(final String value)
            {
                this.articleId = value;
            }

            /**
             * Gets the value of the gtin property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getGtin() {
                return gtin;
            }

            /**
             * Sets the value of the gtin property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setGtin(String value) {
                this.gtin = value;
            }

            /**
             * Gets the value of the quantityDispatched property.
             *
             */
            public int getQuantityDispatched()
            {
                return quantityDispatched;
            }

            /**
             * Sets the value of the quantityDispatched property.
             *
             */
            public void setQuantityDispatched(final int value)
            {
                this.quantityDispatched = value;
            }

        }

    }

}
