//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 05:41:00 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://thebodyshop/orderShipmentConfirmationSchema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package uk.co.thebodyshop.integration.jaxb.order.shipmentconfirmation;
