//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.12 at 03:14:08 PM BST 
//


package uk.co.thebodyshop.integration.jaxb.customer.communicationpreference;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.co.portaltech.tbs.dataprocessing.jaxb.customer.communicationpreference package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.co.portaltech.tbs.dataprocessing.jaxb.customer.communicationpreference
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CustomerCommunicationPreferenceRequest }
     * 
     */
    public CustomerCommunicationPreferenceRequest createCustomerCommunicationPreferenceRequest() {
        return new CustomerCommunicationPreferenceRequest();
    }

    /**
     * Create an instance of {@link CustomerCommunicationPreferenceType }
     * 
     */
    public CustomerCommunicationPreferenceType createCustomerCommunicationPreferenceType() {
        return new CustomerCommunicationPreferenceType();
    }

    /**
     * Create an instance of {@link CustomerCommunicationPreferenceResponse }
     * 
     */
    public CustomerCommunicationPreferenceResponse createCustomerCommunicationPreferenceResponse() {
        return new CustomerCommunicationPreferenceResponse();
    }

    /**
     * Create an instance of {@link CommunicationAddressType }
     * 
     */
    public CommunicationAddressType createCommunicationAddressType() {
        return new CommunicationAddressType();
    }

    /**
     * Create an instance of {@link CommunicationChannelType }
     * 
     */
    public CommunicationChannelType createCommunicationChannelType() {
        return new CommunicationChannelType();
    }

    /**
     * Create an instance of {@link CommunicationPreferenceType }
     * 
     */
    public CommunicationPreferenceType createCommunicationPreferenceType() {
        return new CommunicationPreferenceType();
    }

}
