//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.11 at 10:48:39 AM GMT 
//


package uk.co.thebodyshop.integration.jaxb.skindiagnostic;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.co.portaltech.tbs.dataprocessing.jaxb.skindiagnostic package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.co.portaltech.tbs.dataprocessing.jaxb.skindiagnostic
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CustomerSkinCareDiagnosticsRequest }
     * 
     */
    public CustomerSkinCareDiagnosticsRequest createCustomerSkinCareDiagnosticsRequest() {
        return new CustomerSkinCareDiagnosticsRequest();
    }

    /**
     * Create an instance of {@link SkinCareDiagnosticsResult }
     * 
     */
    public SkinCareDiagnosticsResult createSkinCareDiagnosticsResult() {
        return new SkinCareDiagnosticsResult();
    }

    /**
     * Create an instance of {@link CustomerSkinCareDiagnosticsResponse }
     * 
     */
    public CustomerSkinCareDiagnosticsResponse createCustomerSkinCareDiagnosticsResponse() {
        return new CustomerSkinCareDiagnosticsResponse();
    }

    /**
     * Create an instance of {@link SkinCareDiagnosticsQA }
     * 
     */
    public SkinCareDiagnosticsQA createSkinCareDiagnosticsQA() {
        return new SkinCareDiagnosticsQA();
    }

    /**
     * Create an instance of {@link Articles }
     * 
     */
    public Articles createArticles() {
        return new Articles();
    }

}
