//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.11 at 10:48:39 AM GMT 
//


package uk.co.thebodyshop.integration.jaxb.skindiagnostic;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SkinCareDiagnosticsResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SkinCareDiagnosticsResult">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SkinCareDiagnosticsID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SkinCareDiagnosticsQA" type="{http://www.example.org/CustomerSkinDiagnosticsResult}SkinCareDiagnosticsQA" maxOccurs="unbounded"/>
 *         &lt;element name="Articles" type="{http://www.example.org/CustomerSkinDiagnosticsResult}Articles" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SkinCareDiagnosticsResult", propOrder = {
    "skinCareDiagnosticsID",
    "skinCareDiagnosticsQA",
    "articles"
})
public class SkinCareDiagnosticsResult {

    @XmlElement(name = "SkinCareDiagnosticsID", namespace = "http://www.example.org/CustomerSkinDiagnosticsResult", required = true)
    protected String skinCareDiagnosticsID;
    @XmlElement(name = "SkinCareDiagnosticsQA", namespace = "http://www.example.org/CustomerSkinDiagnosticsResult", required = true)
    protected List<SkinCareDiagnosticsQA> skinCareDiagnosticsQA;
    @XmlElement(name = "Articles", namespace = "http://www.example.org/CustomerSkinDiagnosticsResult", required = true)
    protected List<Articles> articles;

    /**
     * Gets the value of the skinCareDiagnosticsID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkinCareDiagnosticsID() {
        return skinCareDiagnosticsID;
    }

    /**
     * Sets the value of the skinCareDiagnosticsID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkinCareDiagnosticsID(String value) {
        this.skinCareDiagnosticsID = value;
    }

    /**
     * Gets the value of the skinCareDiagnosticsQA property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the skinCareDiagnosticsQA property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSkinCareDiagnosticsQA().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SkinCareDiagnosticsQA }
     * 
     * 
     */
    public List<SkinCareDiagnosticsQA> getSkinCareDiagnosticsQA() {
        if (skinCareDiagnosticsQA == null) {
            skinCareDiagnosticsQA = new ArrayList<SkinCareDiagnosticsQA>();
        }
        return this.skinCareDiagnosticsQA;
    }

    /**
     * Gets the value of the articles property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the articles property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArticles().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Articles }
     * 
     * 
     */
    public List<Articles> getArticles() {
        if (articles == null) {
            articles = new ArrayList<Articles>();
        }
        return this.articles;
    }

}
