//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.31 at 02:16:32 PM GMT 
//


package uk.co.thebodyshop.integration.jaxb.customer.customerprofile;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.co.portaltech.tbs.dataprocessing.jaxb.customer.customerprofile package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.co.portaltech.tbs.dataprocessing.jaxb.customer.customerprofile
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CustomerProfileRequest }
     * 
     */
    public CustomerProfileRequest createCustomerProfileRequest() {
        return new CustomerProfileRequest();
    }

    /**
     * Create an instance of {@link CustomerProfileType }
     * 
     */
    public CustomerProfileType createCustomerProfileType() {
        return new CustomerProfileType();
    }

    /**
     * Create an instance of {@link CustomerProfileResponse }
     * 
     */
    public CustomerProfileResponse createCustomerProfileResponse() {
        return new CustomerProfileResponse();
    }

    /**
     * Create an instance of {@link CommunicationAddressType }
     * 
     */
    public CommunicationAddressType createCommunicationAddressType() {
        return new CommunicationAddressType();
    }

    /**
     * Create an instance of {@link CommunicationChannelType }
     * 
     */
    public CommunicationChannelType createCommunicationChannelType() {
        return new CommunicationChannelType();
    }

    /**
     * Create an instance of {@link CommunicationPreferenceType }
     * 
     */
    public CommunicationPreferenceType createCommunicationPreferenceType() {
        return new CommunicationPreferenceType();
    }

    /**
     * Create an instance of {@link LoyaltyMembershipType }
     * 
     */
    public LoyaltyMembershipType createLoyaltyMembershipType() {
        return new LoyaltyMembershipType();
    }

    /**
     * Create an instance of {@link LoyaltyCardType }
     * 
     */
    public LoyaltyCardType createLoyaltyCardType() {
        return new LoyaltyCardType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

}
