//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.31 at 02:16:32 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://thebodyshop/customerProfileSchema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package uk.co.thebodyshop.integration.jaxb.customer.customerprofile;
