//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.11 at 01:57:07 PM IST 
//


package uk.co.thebodyshop.integration.jaxb.customer.identifier;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CustomerIdentifierMapping" type="{http://thebodyshop/CustomerIdentifierUpdateSchema}CustomerIdentifierMapping" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "customerIdentifierMapping"
})
@XmlRootElement(name = "CustomerIdentifierUpdateRequest")
public class CustomerIdentifierUpdateRequest {

    @XmlElement(name = "CustomerIdentifierMapping", required = true)
    protected List<CustomerIdentifierMapping> customerIdentifierMapping;

    /**
     * Gets the value of the customerIdentifierMapping property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customerIdentifierMapping property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustomerIdentifierMapping().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CustomerIdentifierMapping }
     * 
     * 
     */
    public List<CustomerIdentifierMapping> getCustomerIdentifierMapping() {
        if (customerIdentifierMapping == null) {
            customerIdentifierMapping = new ArrayList<CustomerIdentifierMapping>();
        }
        return this.customerIdentifierMapping;
    }

}
